export enum StepContentIssueEnum {
  MISSING_VARIABLE_IN_PAYLOAD = 'MISSING_VARIABLE_IN_PAYLOAD',
  ILLEGAL_VARIABLE_IN_CONTROL_VALUE = 'ILLEGAL_VARIABLE_IN_CONTROL_VALUE',
  MISSING_VALUE = 'MISSING_VALUE',
}
export enum StepIssueEnum {
  STEP_ID_EXISTS = 'STEP_ID_EXISTS',
  MISSING_REQUIRED_VALUE = 'MISSING_REQUIRED_VALUE',
}
