export enum StepContentIssueEnum {
  MISSING_VARIABLE_IN_PAYLOAD = 'MISSING_VARIABLE_IN_PAYLOAD',
  ILLEGAL_VARIABLE_IN_CONTROL_VALUE = 'ILLEGAL_VARIABLE_IN_CONTROL_VALUE',
  MISSING_VALUE = 'MISSING_VALUE',
  INVALID_URL = 'INVALID_URL',
  TIER_LIMIT_EXCEEDED = 'TIER_LIMIT_EXCEEDED',
}

export enum StepIssueEnum {
  STEP_ID_EXISTS = 'STEP_ID_EXISTS',
  MISSING_REQUIRED_VALUE = 'MISSING_REQUIRED_VALUE',
}

export enum PreviewIssueEnum {
  PREVIEW_ISSUE_REQUIRED_CONTROL_VALUE_IS_MISSING = 'PREVIEW_ISSUE:REQUIRED_CONTROL_VALUE_IS_MISSING',
}
